tofu = Ingredient.create(name: 'Tofu')
lettuce = Ingredient.create(name: 'Lettuce')
onion = Ingredient.create(name: 'Onion')
tomato = Ingredient.create(name: 'Tomato')
bread = Ingredient.create(name: 'Bread')
oil = Ingredient.create(name: 'Oil')
noodles = Ingredient.create(name: 'Noodles')
garlic = Ingredient.create(name: 'Garlic')
cream = Ingredient.create(name: 'Cream')
cheese = Ingredient.create(name: 'Cheese')
mandarin = Ingredient.create(name: 'Mandarin')
soy_sauce = Ingredient.create(name: 'Soy sauce')

Recipe.create(name: 'Tofu Salad', ingredients: [tofu, lettuce, tomato, oil])
Recipe.create(name: 'Tofu Sandwich', ingredients: [tofu, lettuce, tomato, cheese, bread, onion])
Recipe.create(name: 'Pasta Alfredo', ingredients: [cream, cheese, noodles, garlic, oil, onion])
Recipe.create(name: 'Pasta With Tomato Sauce', ingredients: [tomato, noodles, garlic, oil, onion])
Recipe.create(name: 'Lettuce Wrap', ingredients: [tofu, lettuce, garlic, mandarin, soy_sauce, onion])
Recipe.create(name: 'Garlic Bread', ingredients: [bread, cheese, garlic, oil])
