name: CI
on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Is Valid?
        run: docker-compose config

  test-api:
    name: Test API
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13.2-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: react_rails_code_challenge_test
          POSTGRES_USER: majority-labs
          POSTGRES_PASSWORD: password
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Build & Test
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build -t majority-labs/api:${{ github.sha }} \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --network=host \
            --target rspec-tests \
            .
      - name: Scan Image for Vulnerabilities
        uses: docker://docker.io/aquasec/trivy:0.2.1
        continue-on-error: true
        timeout-minutes: 5
        with:
          args: >
            --cache-dir /var/lib/trivy
            --severity "CRITICAL"
            --exit-code 1
            --no-progress
            majority-labs/api:${{ github.sha }}
