name: CI
on: push

jobs:
  test-api:
    name: Test API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Is Valid?
        run: docker-compose config
